#' Generates cumulative calibration plots
#'
#' Plot method for objects returned by [cumulcalib()] and [cumulcalibITE()].
#'
#' @return None
#' @param x An object of class cumulcalib generated by cumulcalib()
#' @param method Which method to use. See details. If unspecified, uses the default method used in the cumulcalib() call.
#' @details
#' For method, options are:
#' BM1p (or simply BM): One-part Brownian motion
#' BM2p: Two-part Brownian motion
#' BB1p: One-part Brownian bridge
#' BB2p (or simply BB): Two-part Brownian bridge
#' @param stats_config A list specifying the visualization parameters for the
#'   statistical test(s). Defaults to an empty list (\code{list()}), which uses
#'   all built-in defaults (e.g., drawing both the statistic and its
#'   significance threshold at the 0.95 level, in blue and red).
#'   If set to \code{NULL}, no statistical lines are drawn.
#'   Recognized elements are \code{sig} (significance level(s)),
#'   \code{lines} (which lines to draw: include \code{"v"} for the vertical
#'   statistic line and/or \code{"h"} for the horizontal significance
#'   threshold), and \code{col} (color(s)).
#' @param x2axis If true, draws a second x-axis (on top) showing predicted risks
#' @param y2axis If true, draws a second y-axis (on right) showing scaled partial sums
#' @param draw_polygon If true, draws the black triangle marker at the origin. Default is TRUE
#' @param ... Parameters to be passed to plot()
#' @method plot cumulcalib
#' @export
plot.cumulcalib <- function(
  x,
  method = NULL,
  stats_config = list(),
  x2axis = TRUE,
  y2axis = TRUE,
  draw_polygon = TRUE,
  ...
) {
  if (is.null(method)) {
    method <- x$method
  } else {
    if (length(method) > 1) {
      stop("Only one method can be equested.")
    }
    if (!(method %in% names(x$by_method))) {
      stop(paste(
        "The requested method has not been provided by the original cumulcalib() call. You asked for",
        method,
        "but the submitted object has method(s)",
        paste(names(x$by_method), collapse = ",")
      ))
    }
  }

  oldpar <- par(no.readonly = TRUE)
  on.exit(par(oldpar))

  args <- list(...)

  t_ <- x$data[, 't']
  X <- x$data[, 'X']
  W <- x$data[, 'S']
  n <- length(W)
  loc <- x$by_method[[method]]$loc

  stat_lines <- data.frame(
    x1 = double(),
    x2 = double(),
    y1 = double(),
    y2 = double(),
    lty = integer(),
    col = character()
  )

  if (method %in% c("BM2p", "BB", "BB2p")) {
    is_2p <- TRUE
    switch(
      1 + length(stats_config$sig),
      {
        stats_config$sig <- rep(0.95, 2)
      },
      {
        stats_config$sig <- rep(stats_config$sig, 2)
      },
      {},
      {
        stop("Too many values for stats_config$sig")
      }
    )
    switch(
      1 + length(stats_config$lines),
      {
        stats_config$lines <- c("vh", "vh")
      },
      {
        stats_config$lines <- rep(stats_config$lines, 2)
      },
      {},
      {
        stop("Too many values for stats_config$lines")
      }
    )
    switch(
      1 + length(stats_config$col),
      {
        stats_config$col <- c("blue", "red")
      },
      {
        stats_config$col <- rep(stats_config$col, 2)
      },
      {},
      {
        stop("Too many values for stats_config$col")
      }
    )
  } else {
    is_2p <- FALSE
    switch(
      1 + length(stats_config$sig),
      {
        stats_config$sig <- rep(0.95, 1)
      },
      {},
      {
        stop("Too many values for stats_config$sig")
      }
    )
    switch(
      1 + length(stats_config$lines),
      {
        stats_config$lines <- "vh"
      },
      {},
      {
        stop("Too many values for stats_config$lines")
      }
    )
    switch(
      1 + length(stats_config$col),
      {
        stats_config$col <- c("red")
      },
      {},
      {
        stop("Too many values for stats_config$col")
      }
    )
  }
  is_bridge <- FALSE
  if (method %in% c("BB", "BB1p", "BB2p")) {
    is_bridge <- TRUE
  }

  if (!is.null(stats_config)) {
    i_conf <- 1

    if (is_2p) {
      if (grepl("v", stats_config$lines[i_conf], ignore.case = TRUE)) {
        stat_lines[1 + nrow(stat_lines), ] <- list(
          1,
          1,
          0,
          W[n],
          1,
          stats_config$col[i_conf]
        )
      }
      if (grepl("h", stats_config$lines[i_conf], ignore.case = TRUE)) {
        sig_p1 <- stats::qnorm(1 - (1 - stats_config$sig[1]) / 2)
        stat_lines[1 + nrow(stat_lines), ] <- list(
          0,
          1,
          sign(W[n]) * sig_p1,
          sign(W[n]) * sig_p1,
          4,
          stats_config$col[i_conf]
        )
      }
      i_conf <- i_conf + 1
    }

    if (grepl("v", stats_config$lines[i_conf], ignore.case = TRUE)) {
      if (is_bridge) {
        stat_lines[1 + nrow(stat_lines), ] <- list(
          t_[loc],
          t_[loc],
          t_[loc] * W[n],
          W[loc],
          1,
          stats_config$col[i_conf]
        )
        stat_lines[1 + nrow(stat_lines), ] <- list(
          0,
          1,
          0,
          W[n],
          1,
          "grey"
        )
      } else {
        stat_lines[1 + nrow(stat_lines), ] <- list(
          t_[loc],
          t_[loc],
          0,
          W[loc],
          1,
          stats_config$col[i_conf]
        )
        stat_lines[1 + nrow(stat_lines), ] <- list(
          0,
          1,
          0,
          0,
          1,
          "grey"
        )
      }
    }
    if (grepl("h", stats_config$lines[i_conf], ignore.case = TRUE)) {
      if (is_bridge) {
        sig_p2 <- qKolmogorov(stats_config$sig[i_conf])
        #Significance band runs parallel to the bridge (start-to-end) line,
        #offset by the Kolmogorov critical value on the side of the max deviation
        sign_p2 <- sign(W[loc] - t_[loc] * W[n])
        stat_lines[1 + nrow(stat_lines), ] <- list(
          0,
          1,
          sign_p2 * sig_p2,
          sign_p2 * sig_p2 + W[n],
          4,
          stats_config$col[i_conf]
        )
      } else {
        if (is_2p) {
          sig_p2 <- qMAD_BM_c(
            stats_config$sig[i_conf],
            w1 = W[n]
          )
        } else {
          sig_p2 <- qMAD_BM(stats_config$sig[i_conf])
        }
        stat_lines[1 + nrow(stat_lines), ] <- list(
          0,
          1,
          sign(W[loc]) * sig_p2,
          sign(W[loc]) * sig_p2,
          4,
          stats_config$col[i_conf]
        )
      }
    }
    i_conf <- i_conf + 1
  }

  i <- match("xlim", names(args))
  if (is.na(i)) {
    args$xlim <- c(-0.03, 1.01)
  }
  i <- match("ylim", names(args))
  if (is.na(i)) {
    args$ylim <- c(
      min(W, stat_lines$y1, stat_lines$y2, ifelse(draw_polygon, -1, 0)),
      max(W, stat_lines$y1, stat_lines$y2, ifelse(draw_polygon, 1, 0))
    )
  }
  i <- match("type", names(args))
  if (is.na(i)) {
    args$type <- 'l'
  }
  i <- match("xaxt", names(args))
  if (is.na(i)) {
    args$xaxt <- 'n'
  }
  i <- match("yaxt", names(args))
  if (is.na(i)) {
    args$yaxt <- 'n'
  }
  i <- match("xlab", names(args))
  if (is.na(i)) {
    args$xlab <- 'Time'
  }
  i <- match("ylab", names(args))
  if (is.na(i)) {
    args$ylab <- 'Standardized cumulative sum'
  }

  args$x <- t_
  args$y <- W

  args$xaxs <- 'i'

  par(mar = c(3, 3, ifelse(x2axis, 3, 1), ifelse(y2axis, 3, 1)))

  do.call(plot, args)

  #Axes
  axis(1, line = 0, at = (0:10) / 10, labels = (0:10) / 10, padj = 0)
  mtext(args$xlab, 1, line = 2)

  axis(side = 2, at = pretty(args$ylim), padj = 0)
  mtext(args$ylab, 2, line = 2)

  if (x2axis) {
    xs <- round(
      unlist(lapply((0:10) / 10, function(z) {
        x$data[which.min((x$data[, 't'] - z)^2), 'X']
      })),
      3
    )
    axis(side = 3, at = (0:10) / 10, labels = xs, padj = 0)
    mtext("Predicted values", 3, line = 2) #expression(pi) for label will generate the symbol!
  }

  if (y2axis) {
    scale <- n / sqrt(x$T)
    y2p <- pretty(args$ylim / scale)
    axis(side = 4, at = y2p * scale, labels = y2p, padj = 0)
    mtext('Scaled cumulative sum', 4, line = 2)
  }

  #Triangle
  if (draw_polygon) {
    polygon(x = c(0, -0.03, -0.03), y = c(0, -1, 1), col = 'black')
  }

  if (nrow(stat_lines) > 0) {
    for (i in 1:nrow(stat_lines)) {
      lines(
        stat_lines[i, 1:2],
        stat_lines[i, 3:4],
        lty = stat_lines[i, 'lty'],
        col = stat_lines[i, 'col']
      )
    }
  }
}
